title: Introduction to Programming in C

description: >-
  Introductory course where we are going to see how to compile and execute C
  programs, and the main types of variables and flow control statements of this
  programming language.

template:
  repo: introduction-to-programming-in-c-template
  name: introduction-to-programming-in-c

before:
  - type: createIssue
    title: Hello, World!
    body: 01_hello-world.md
    store:
      issue_01_url: '{{ result.data.html_url }}'
      issue_01_id: '{{ result.data.id }}'

steps:

#1
  - title: Compile and run your first C program
    description: Install the GCC compiler, and compile and run a basic Hello World C program
    event: issues.assigned
    link: '{{ store.issue_01_url }}'
    actions:
      - type: closeIssue
        issue: '{{ store.issue_01_id }}'
